In [25]:
import numpy as np
class NN:
    def __init__(self):
        self.w1=np.random.randn(4,4)
        self.b1=np.zeros((1,4))
        self.w2=np.random.randn(4,1)
        self.b2=np.zeros((1,1))
    def sigmoid(self,z):
        return 1/(1+np.exp(-z))
    def sigmoid_derivate(self,x):
        return x*(1-x)
    def forward_prop(self,x):
        self.z1=np.dot(x,self.w1)+self.b1
        self.a1=self.sigmoid(self.z1)
        self.z2=np.dot(self.a1,self.w2)+self.b2
        self.a2=self.sigmoid(self.z2)
        return self.a2
    def back_prop(self,x,y,lr=0.1):
        
        m=x.shape[0]
        
        dz2=self.a2-y
        dw2=(1/m)*np.dot(self.a1.T,dz2)
        db2=(1/m)*np.sum(dz2,axis=0,keepdims=True)
        
        dz1=np.dot(dz2,self.w2.T)*self.sigmoid_derivate(self.a1)
        dw1=(1/m)*np.dot(x.T,dz1)
        db1=(1/m)*np.sum(dz1,axis=0,keepdims=True)
        
        self.w1-=lr*dw1
        self.b1-=lr*db1
        self.w2-=lr*dw2
        self.b2-=lr*db2
        

In [26]:
x=np.asarray([[0,0,0,0],[0,0,0,1],[0,0,1,0],[0,0,1,1],[0,1,0,0],[0,1,0,1],[0,1,1,0],[0,1,1,1],[1,0,0,0],[1,0,0,1],[1,0,1,0]])
y=np.asarray([[0],[1],[0],[1],[0],[1],[0],[1],[0],[1],[0]])
nn=NN()
for i in range(1000):
    a=nn.forward_prop(x)
    nn.back_prop(x,y)
    if i % 100 == 0:
        loss = np.mean((y - a)**2)
        print(f"Epoch {i}, Loss: {loss:.4f}")
pred=nn.forward_prop(x)

Epoch 0, Loss: 0.2162
Epoch 100, Loss: 0.1170
Epoch 200, Loss: 0.0541
Epoch 300, Loss: 0.0245
Epoch 400, Loss: 0.0120
Epoch 500, Loss: 0.0066
Epoch 600, Loss: 0.0039
Epoch 700, Loss: 0.0026
Epoch 800, Loss: 0.0018
Epoch 900, Loss: 0.0013


In [27]:
print("input \t output 'y' \t prediction 'y-hat'")
for i in range(pred.shape[0]):
    print(x[i]," \t    ",y[i][0],"\t\t   ",round(pred[i][0]))

input 	 output 'y' 	 prediction 'y-hat'
[0 0 0 0]  	     0 		    0
[0 0 0 1]  	     1 		    1
[0 0 1 0]  	     0 		    0
[0 0 1 1]  	     1 		    1
[0 1 0 0]  	     0 		    0
[0 1 0 1]  	     1 		    1
[0 1 1 0]  	     0 		    0
[0 1 1 1]  	     1 		    1
[1 0 0 0]  	     0 		    0
[1 0 0 1]  	     1 		    1
[1 0 1 0]  	     0 		    0


In [30]:
nn.forward_prop([[1,1,0,0]]) #12

array([[0.02222383]])

In [31]:
nn.forward_prop([[1,1,0,1]]) #13

array([[0.9598149]])